# Generated by Django 2.0.3 on 2018-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='follow_him',
            new_name='follows',
        ),
    ]
