# Generated by Django 2.0.3 on 2018-03-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180329_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follows',
        ),
        migrations.AddField(
            model_name='user',
            name='follow_him',
            field=models.ManyToManyField(related_name='follow_he', to='news.User'),
        ),
    ]
