# Generated by Django 2.0.3 on 2018-03-31 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follow_him',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
