# Generated by Django 2.0.3 on 2018-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180401_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='user'),
        ),
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
