# Generated by Django 2.0.3 on 2018-04-15 15:34

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20180412_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(null=True, upload_to=news.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=news.models.post_directory_path),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=256),
        ),
    ]
