# Generated by Django 2.0.3 on 2018-04-27 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20180427_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
